#!/bin/bash

###
# Copyright 2018 Cober Solutions
#
# Author: Alan Drees
#
# Purpose: Parse the docker-compose dotenv file TAG into it's maj/min/rev parts
###

DOTENV_FILE=''
VERSION_DIR=

###
#
# Allow the user the specify the path to the dotenv file
#
###
if [ -f "$1" ]
then
    DOTENV_FILE="$1"
else
    DOTENV_FILE='./.env'
fi

###
#
# Allow the user the specify the path to where the files should be output
#
###
if [ -n "$2" ]
then
    VERSION_PATH="$2"
else
    VERSION_PATH="/version"
fi

###
#
# Load the dotenv file into the current environment
#
###
source "$DOTENV_FILE"

###
#
# Parse out the maj/min/rev parameters from the TAG variable
#
###
MAJOR=$(echo $TAG | awk -F '.' '{print $1}')
MINOR=$(echo $TAG | awk -F '.' '{print $2}')
PATCH=$(echo $TAG | awk -F '.' '{print $3}')



###
#
# Create the version directory
#
###
mkdir $VERSION_PATH

###
#
# Output the constituant parts into their respective files
#
###
echo $MAJOR > $VERSION_PATH/major
echo $MINOR > $VERSION_PATH/minor
echo $REVISION > $VERSION_PATH/rev
